{{- if .Values.admin.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- range $key, $value := .Values.admin.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: cms-admin
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.admin.ingress.ingressClassName }}
  {{- if .Values.admin.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.admin.ingress.tls.secretName }}
      hosts:
        - {{ .Values.admin.ingress.host }}
  {{- end }}
  rules:
  - host: {{ .Values.admin.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: cms-admin
            port:
              number: 8889
        path: /
        pathType: Prefix
{{- end }}