apiVersion: v1
kind: Service
metadata:
  labels:
    app: cms-contest
  name: cms-contest
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
    name: contest
  selector:
    app: cms-contest
  type: {{ .Values.contest.serviceType }}